Context Alert Filter
jenkinsci/zap-plugin pull request #2
Opened 2017-01-19 09:38 UTC by tlenaic

I am developing the feature "context alert filter" for jenkins.

Write now i have :

   -  add the section on Jelly.
    - The xml file should be in the directory filters of our job jenkins
    - I can parse my xml file
    - call the api alertfilter and addAlertFilter .

i am running some test now and my question is ruleId in the methode addAlertFilter of the class AlertFilter corresponds to what ?

My question is how could i find the id of my scanner (sql injection,...) ?

is it the value of pluginId in my ZAP xml report

thanks

frank

2017-01-19 17:03 UTC, tlenaic commented
i don't now, if my question have been seen on the other link.
i want to know, if  in the methode addAlertFilter of the class AlertFilter, the string ruleId corresponds to the value of pluginId in my ZAP xml report ?

AND  for now, i am in my algorithm
 - i parse the xml file
 - add filters to the context
 - finally i run the active scan

do i, have miss a step ? because there is no changes in the report. 
i dont know if the method active scan check for filter in my context.
( I WORK with a session in jenkins without alerts, i erase all of them and i make sure the session was saved without )

2017-01-20 14:06 UTC, tlenaic commented
i finally implemented correctly the feature.
and i have add logged out indicator because i need it in a project.
It is important to know that, the plugin use the unrelease version of zap-api-java. i needed the class alertFilter.

2017-03-10 14:33 UTC, JordanGS commented
@tlenaic Hi, thank you for the contribution. I'll be checking over the PR over the weekend as well as the failure status that jenkins detected and let you know.

2017-03-10 14:45 UTC, tlenaic commented
for this PR, the failure status is because i was using the alertfilter function. who is not present in the version 1.0.0 of zap-api realese.
i am preparing a correct one with zap-api 1.1.1 logged outindicator context alert filter and post build  step -->Management threshold

2017-03-10 14:47 UTC, JordanGS commented
@tlenaic Hold off on any changes, I'll merge PR#3 in before yours. THen you can just merge those changes into your request since they contain fixed API calls. Is that okay?

2017-03-10 14:54 UTC, tlenaic commented
okay

2017-03-10 14:55 UTC, JordanGS commented
@tlenaic waiting on an issue from jenkinsci in relation to the build server. We'll talk on Sunday/Monday. Cheers mate.

2017-03-13 04:06 UTC, JordanGS commented
@tlenaic New version is out and merged into master and development. Using API 1.1.1, feel free to update.

2017-03-13 14:28 UTC, JordanGS commented
@tlenaic Can you squash the commits and more importantly rebase. That way it's all one commit and one commit message.

I'll test your PR tonight and tomorrow after work. Thanks!

2017-03-13 14:41 UTC, JordanGS requested changes

2017-03-13 14:41 UTC, JordanGS commented on src/main/java/org/jenkinsci/plugins/zap/ZAPBuilder.java
> +import hudson.model.*;
No wildcard imports, the previous was intentional.

```
import hudson.model.AbstractBuild;
import hudson.model.AbstractProject;
import hudson.model.BuildListener;
import hudson.model.Computer;
import hudson.model.Node;
```

2017-03-13 14:41 UTC, JordanGS commented on src/main/java/org/jenkinsci/plugins/zap/ZAPBuilder.java
> + * @author Lenaic Tchokogoue
Most recent contributor at the top of the list.

2017-03-13 14:41 UTC, JordanGS commented on src/main/java/org/jenkinsci/plugins/zap/ZAPBuilder.java
> +        //return res;
Excess comment.

2017-03-16 16:36 UTC, thc202 commented
Closing, there's a newer pull request (#4).

2017-03-16 16:36 UTC, closed without merging